### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by brpaz** [tinytacoteam/zazu-template#1]
Hello.
The example tests arent working anymore since the removing of "root script".
Is there a way I can write tests for my plugin?

I would like to be able to simulate the execution of my plugin and check if the results are the expected ones based on the search query, but the plugin code is just a function which receives the plugin context.
I cant see how I can execute the plugin code for tests.

Any ideas?

**Comment by bayleedev** [comment]
I just fixed the tests in 4913befcb845c11c73250c05df19f3b0e388e466

If you want specific help on how to test your code, do you mind pointing me to your repo? Thanks!

**Comment by brpaz** [comment]
Great. I have managed to understand how to write tests for my plugins thanks to the new example.
